from __future__ import annotations

from copy import deepcopy


SEED_ENTITIES: list[dict] = [
    {
        "canonical_name": "Python",
        "canonical_slug": "python",
        "aliases": ["py"],
        "editorial_kind": "language",
        "topic_family": "general-purpose",
        "implementation_languages": ["python"],
        "ecosystems": ["pypi"],
        "description": "General-purpose language with dominant reach across backend, data, and automation.",
    },
    {
        "canonical_name": "TypeScript",
        "canonical_slug": "typescript",
        "aliases": ["ts"],
        "editorial_kind": "language",
        "topic_family": "application",
        "implementation_languages": ["typescript", "javascript"],
        "ecosystems": ["npm"],
        "description": "Typed superset of JavaScript that anchors modern frontend and full-stack development.",
    },
    {
        "canonical_name": "Go",
        "canonical_slug": "go",
        "aliases": ["golang"],
        "editorial_kind": "language",
        "topic_family": "cloud",
        "implementation_languages": ["go"],
        "ecosystems": ["go"],
        "description": "Compiled language optimized for cloud services, infrastructure, and operational simplicity.",
    },
    {
        "canonical_name": "Rust",
        "canonical_slug": "rust",
        "aliases": ["rustlang"],
        "editorial_kind": "language",
        "topic_family": "systems",
        "implementation_languages": ["rust"],
        "ecosystems": ["cargo"],
        "description": "Memory-safe systems language increasingly used in infrastructure, tooling, and performance-sensitive services.",
    },
    {
        "canonical_name": "Java",
        "canonical_slug": "java",
        "aliases": [],
        "editorial_kind": "language",
        "topic_family": "enterprise",
        "implementation_languages": ["java"],
        "ecosystems": ["maven"],
        "description": "Enterprise runtime with broad platform support and sustained large-scale adoption.",
    },
    {
        "canonical_name": "JavaScript",
        "canonical_slug": "javascript",
        "aliases": ["js", "node", "nodejs"],
        "editorial_kind": "language",
        "topic_family": "application",
        "implementation_languages": ["javascript"],
        "ecosystems": ["npm"],
        "description": "Ubiquitous web language that still anchors browser execution and a large share of server-side tooling.",
    },
    {
        "canonical_name": "Kotlin",
        "canonical_slug": "kotlin",
        "aliases": [],
        "editorial_kind": "language",
        "topic_family": "application",
        "implementation_languages": ["kotlin"],
        "ecosystems": ["maven", "gradle"],
        "description": "JVM language with strong Android reach and steady use for modern backend services.",
    },
    {
        "canonical_name": "C#",
        "canonical_slug": "csharp",
        "aliases": ["c#", "dotnet", ".net"],
        "editorial_kind": "language",
        "topic_family": "enterprise",
        "implementation_languages": ["c#"],
        "ecosystems": ["nuget"],
        "description": "Mature language for business systems, cloud services, and game development on the .NET platform.",
    },
    {
        "canonical_name": "PHP",
        "canonical_slug": "php",
        "aliases": [],
        "editorial_kind": "language",
        "topic_family": "web",
        "implementation_languages": ["php"],
        "ecosystems": ["composer"],
        "description": "Still-relevant web language with a large installed base across content, commerce, and internal systems.",
    },
    {
        "canonical_name": "Ruby",
        "canonical_slug": "ruby",
        "aliases": [],
        "editorial_kind": "language",
        "topic_family": "web",
        "implementation_languages": ["ruby"],
        "ecosystems": ["rubygems"],
        "description": "Developer-friendly language that remains relevant in product teams and automation-heavy workflows.",
    },
    {
        "canonical_name": "Swift",
        "canonical_slug": "swift",
        "aliases": [],
        "editorial_kind": "language",
        "topic_family": "mobile",
        "implementation_languages": ["swift"],
        "ecosystems": ["swiftpm", "ios"],
        "description": "Primary language for Apple platform development with strong ongoing ecosystem investment.",
    },
    {
        "canonical_name": "Scala",
        "canonical_slug": "scala",
        "aliases": [],
        "editorial_kind": "language",
        "topic_family": "data",
        "implementation_languages": ["scala"],
        "ecosystems": ["maven", "sbt"],
        "description": "JVM language still present in data-intensive systems and functional-leaning backend teams.",
    },
    {
        "canonical_name": "C++",
        "canonical_slug": "cpp",
        "aliases": ["c++", "cpp"],
        "editorial_kind": "language",
        "topic_family": "systems",
        "implementation_languages": ["c++"],
        "ecosystems": ["cmake"],
        "description": "Systems language with continued importance in performance-critical infrastructure and client software.",
    },
    {
        "canonical_name": "Elixir",
        "canonical_slug": "elixir",
        "aliases": [],
        "editorial_kind": "language",
        "topic_family": "concurrency",
        "implementation_languages": ["elixir"],
        "ecosystems": ["hex"],
        "description": "BEAM language valued for highly concurrent systems and resilient application design.",
    },
    {
        "canonical_name": "Dart",
        "canonical_slug": "dart",
        "aliases": [],
        "editorial_kind": "language",
        "topic_family": "application",
        "implementation_languages": ["dart"],
        "ecosystems": ["pub"],
        "description": "Application language primarily relevant through Flutter and cross-platform client development.",
    },
    {
        "canonical_name": "Haskell",
        "canonical_slug": "haskell",
        "aliases": [],
        "editorial_kind": "language",
        "topic_family": "functional",
        "implementation_languages": ["haskell"],
        "ecosystems": ["hackage"],
        "description": "Functional language with niche but real influence in correctness-oriented and research-adjacent systems.",
    },
    {
        "canonical_name": "Zig",
        "canonical_slug": "zig",
        "aliases": [],
        "editorial_kind": "language",
        "topic_family": "systems",
        "implementation_languages": ["zig"],
        "ecosystems": ["zig"],
        "description": "Emerging systems language gaining attention as a pragmatic alternative for low-level tooling and infrastructure work.",
    },
    {
        "canonical_name": "React",
        "canonical_slug": "react",
        "aliases": ["reactjs"],
        "editorial_kind": "framework",
        "topic_family": "ui",
        "implementation_languages": ["javascript", "typescript"],
        "ecosystems": ["npm"],
        "description": "Component model that remains the default reference point for web UI engineering.",
    },
    {
        "canonical_name": "Next.js",
        "canonical_slug": "nextjs",
        "aliases": ["next.js", "next"],
        "editorial_kind": "framework",
        "topic_family": "web-platform",
        "implementation_languages": ["typescript", "javascript"],
        "ecosystems": ["npm"],
        "description": "Full-stack React framework with strong defaults for SSR, routing, and deployment integration.",
    },
    {
        "canonical_name": "FastAPI",
        "canonical_slug": "fastapi",
        "aliases": [],
        "editorial_kind": "framework",
        "topic_family": "api",
        "implementation_languages": ["python"],
        "ecosystems": ["pypi"],
        "description": "Python API framework favored for modern typed services and AI-adjacent backends.",
    },
    {
        "canonical_name": "Django",
        "canonical_slug": "django",
        "aliases": [],
        "editorial_kind": "framework",
        "topic_family": "web",
        "implementation_languages": ["python"],
        "ecosystems": ["pypi"],
        "description": "Mature batteries-included framework for web products and back-office systems.",
    },
    {
        "canonical_name": "Spring Boot",
        "canonical_slug": "spring-boot",
        "aliases": ["spring", "spring boot"],
        "editorial_kind": "framework",
        "topic_family": "enterprise",
        "implementation_languages": ["java", "kotlin"],
        "ecosystems": ["maven"],
        "description": "Default application framework for modern JVM services in large organizations.",
    },
    {
        "canonical_name": "Vue.js",
        "canonical_slug": "vuejs",
        "aliases": ["vue", "vue.js"],
        "editorial_kind": "framework",
        "topic_family": "ui",
        "implementation_languages": ["javascript", "typescript"],
        "ecosystems": ["npm"],
        "description": "Frontend framework with a strong ergonomics story for teams that prefer incremental adoption.",
    },
    {
        "canonical_name": "Angular",
        "canonical_slug": "angular",
        "aliases": ["angularjs"],
        "editorial_kind": "framework",
        "topic_family": "enterprise-web",
        "implementation_languages": ["typescript"],
        "ecosystems": ["npm"],
        "description": "Opinionated frontend framework with deep enterprise presence and end-to-end conventions.",
    },
    {
        "canonical_name": "Express",
        "canonical_slug": "express",
        "aliases": ["expressjs"],
        "editorial_kind": "framework",
        "topic_family": "api",
        "implementation_languages": ["javascript", "typescript"],
        "ecosystems": ["npm"],
        "description": "Minimal Node.js web framework that still underpins a large amount of service and middleware code.",
    },
    {
        "canonical_name": "Laravel",
        "canonical_slug": "laravel",
        "aliases": [],
        "editorial_kind": "framework",
        "topic_family": "web",
        "implementation_languages": ["php"],
        "ecosystems": ["composer"],
        "description": "Full-stack PHP framework with durable adoption for business applications and content-heavy products.",
    },
    {
        "canonical_name": "Ruby on Rails",
        "canonical_slug": "rails",
        "aliases": ["rails", "ruby on rails"],
        "editorial_kind": "framework",
        "topic_family": "web",
        "implementation_languages": ["ruby"],
        "ecosystems": ["rubygems"],
        "description": "Opinionated web framework that still shapes product delivery patterns and startup engineering defaults.",
    },
    {
        "canonical_name": "Flask",
        "canonical_slug": "flask",
        "aliases": [],
        "editorial_kind": "framework",
        "topic_family": "api",
        "implementation_languages": ["python"],
        "ecosystems": ["pypi"],
        "description": "Minimal Python web framework widely used for services, internal tools, and lightweight APIs.",
    },
    {
        "canonical_name": "NestJS",
        "canonical_slug": "nestjs",
        "aliases": ["nest", "nest.js"],
        "editorial_kind": "framework",
        "topic_family": "api",
        "implementation_languages": ["typescript", "javascript"],
        "ecosystems": ["npm"],
        "description": "Structured TypeScript backend framework popular with teams that want opinionated Node.js service architecture.",
    },
    {
        "canonical_name": "Nuxt",
        "canonical_slug": "nuxt",
        "aliases": ["nuxtjs", "nuxt.js"],
        "editorial_kind": "framework",
        "topic_family": "web-platform",
        "implementation_languages": ["typescript", "javascript"],
        "ecosystems": ["npm"],
        "description": "Vue-based full-stack framework with strong adoption in content-heavy and frontend-led web platforms.",
    },
    {
        "canonical_name": "SvelteKit",
        "canonical_slug": "sveltekit",
        "aliases": ["svelte kit"],
        "editorial_kind": "framework",
        "topic_family": "web-platform",
        "implementation_languages": ["typescript", "javascript"],
        "ecosystems": ["npm"],
        "description": "Modern web framework built around Svelte with strong developer experience and performance positioning.",
    },
    {
        "canonical_name": "ASP.NET Core",
        "canonical_slug": "aspnet-core",
        "aliases": ["asp.net core", "aspnet"],
        "editorial_kind": "framework",
        "topic_family": "enterprise",
        "implementation_languages": ["c#"],
        "ecosystems": ["nuget"],
        "description": "Mainstream .NET application framework for APIs, web apps, and enterprise service platforms.",
    },
    {
        "canonical_name": "Remix",
        "canonical_slug": "remix",
        "aliases": [],
        "editorial_kind": "framework",
        "topic_family": "web-platform",
        "implementation_languages": ["typescript", "javascript"],
        "ecosystems": ["npm"],
        "description": "React-based web framework with a strong server-first model and increasingly visible production usage.",
    },
    {
        "canonical_name": "Phoenix",
        "canonical_slug": "phoenix",
        "aliases": [],
        "editorial_kind": "framework",
        "topic_family": "web",
        "implementation_languages": ["elixir"],
        "ecosystems": ["hex"],
        "description": "Elixir framework valued for real-time workloads, concurrency, and operational resilience.",
    },
    {
        "canonical_name": "Playwright",
        "canonical_slug": "playwright",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "testing",
        "implementation_languages": ["typescript", "python", "java", "c#"],
        "ecosystems": ["npm", "pypi", "maven", "nuget"],
        "description": "End-to-end testing tool with strong browser coverage and modern automation ergonomics.",
    },
    {
        "canonical_name": "Docker",
        "canonical_slug": "docker",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "containers",
        "implementation_languages": ["go"],
        "ecosystems": ["docker"],
        "description": "Container packaging toolchain that remains foundational to developer workflows.",
    },
    {
        "canonical_name": "Terraform",
        "canonical_slug": "terraform",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "infrastructure",
        "implementation_languages": ["go"],
        "ecosystems": ["terraform"],
        "description": "Infrastructure as code tool with broad enterprise footprint across cloud provisioning.",
    },
    {
        "canonical_name": "GitHub Actions",
        "canonical_slug": "github-actions",
        "aliases": ["github actions"],
        "editorial_kind": "tool",
        "topic_family": "delivery",
        "implementation_languages": ["yaml", "javascript"],
        "ecosystems": ["github"],
        "description": "Integrated CI/CD automation layer embedded in mainstream source control workflows.",
    },
    {
        "canonical_name": "Cursor",
        "canonical_slug": "cursor",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "ai-devex",
        "implementation_languages": ["typescript"],
        "ecosystems": ["desktop"],
        "description": "AI-assisted development environment shaping current developer workflow expectations.",
    },
    {
        "canonical_name": "pnpm",
        "canonical_slug": "pnpm",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "package-management",
        "implementation_languages": ["typescript", "javascript"],
        "ecosystems": ["npm"],
        "description": "Package manager chosen for monorepo efficiency, deterministic installs, and workspace ergonomics.",
    },
    {
        "canonical_name": "Helm",
        "canonical_slug": "helm",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "kubernetes",
        "implementation_languages": ["go"],
        "ecosystems": ["kubernetes"],
        "description": "Kubernetes packaging tool that remains common in platform teams and deployment workflows.",
    },
    {
        "canonical_name": "VS Code",
        "canonical_slug": "vs-code",
        "aliases": ["vscode", "visual studio code"],
        "editorial_kind": "tool",
        "topic_family": "developer-environment",
        "implementation_languages": ["typescript"],
        "ecosystems": ["desktop"],
        "description": "Mainstream development environment that continues to set expectations for editor extensibility and workflow integration.",
    },
    {
        "canonical_name": "GitLab CI",
        "canonical_slug": "gitlab-ci",
        "aliases": ["gitlab ci", "gitlab ci/cd"],
        "editorial_kind": "tool",
        "topic_family": "delivery",
        "implementation_languages": ["yaml", "ruby"],
        "ecosystems": ["gitlab"],
        "description": "Integrated delivery automation stack used by teams that standardize around GitLab as a platform.",
    },
    {
        "canonical_name": "GitHub Copilot",
        "canonical_slug": "github-copilot",
        "aliases": ["copilot", "github copilot"],
        "editorial_kind": "tool",
        "topic_family": "ai-devex",
        "implementation_languages": [],
        "ecosystems": ["desktop", "github"],
        "description": "Mainstream AI coding assistant that has materially shifted developer workflow expectations.",
    },
    {
        "canonical_name": "Jenkins",
        "canonical_slug": "jenkins",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "delivery",
        "implementation_languages": ["java"],
        "ecosystems": ["ci"],
        "description": "Long-standing CI automation server that still appears across legacy and enterprise build estates.",
    },
    {
        "canonical_name": "Postman",
        "canonical_slug": "postman",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "api",
        "implementation_languages": [],
        "ecosystems": ["desktop", "web"],
        "description": "API development toolchain commonly used for exploration, collaboration, and test workflow handoff.",
    },
    {
        "canonical_name": "Pulumi",
        "canonical_slug": "pulumi",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "infrastructure",
        "implementation_languages": ["typescript", "python", "go", "c#"],
        "ecosystems": ["cloud"],
        "description": "Infrastructure as code tool that appeals to teams wanting general-purpose languages over DSLs.",
    },
    {
        "canonical_name": "Ansible",
        "canonical_slug": "ansible",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "automation",
        "implementation_languages": ["python"],
        "ecosystems": ["automation"],
        "description": "Automation and configuration management tool with enduring use in ops-heavy and hybrid estates.",
    },
    {
        "canonical_name": "Argo CD",
        "canonical_slug": "argo-cd",
        "aliases": ["argocd", "argo cd"],
        "editorial_kind": "tool",
        "topic_family": "delivery",
        "implementation_languages": ["go"],
        "ecosystems": ["kubernetes"],
        "description": "GitOps delivery tool widely adopted by Kubernetes platform teams for declarative deployment flows.",
    },
    {
        "canonical_name": "uv",
        "canonical_slug": "uv",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "package-management",
        "implementation_languages": ["rust", "python"],
        "ecosystems": ["pypi"],
        "description": "Fast Python packaging and environment tool that is quickly gaining adoption in modern Python workflows.",
    },
    {
        "canonical_name": "Nix",
        "canonical_slug": "nix",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "developer-environment",
        "implementation_languages": [],
        "ecosystems": ["devops"],
        "description": "Reproducibility-focused tooling increasingly used for consistent developer environments and build pipelines.",
    },
    {
        "canonical_name": "AWS",
        "canonical_slug": "aws",
        "aliases": ["amazon web services"],
        "editorial_kind": "platform",
        "topic_family": "cloud",
        "implementation_languages": [],
        "ecosystems": ["cloud"],
        "description": "General-purpose cloud platform with the widest service surface and enterprise footprint.",
    },
    {
        "canonical_name": "Kubernetes",
        "canonical_slug": "kubernetes",
        "aliases": ["k8s"],
        "editorial_kind": "platform",
        "topic_family": "orchestration",
        "implementation_languages": ["go"],
        "ecosystems": ["cloud", "kubernetes"],
        "description": "Container orchestration platform that defines the control plane model for many teams.",
    },
    {
        "canonical_name": "Cloudflare",
        "canonical_slug": "cloudflare",
        "aliases": [],
        "editorial_kind": "platform",
        "topic_family": "edge",
        "implementation_languages": [],
        "ecosystems": ["edge"],
        "description": "Edge platform increasingly used for delivery, compute, and security consolidation.",
    },
    {
        "canonical_name": "Vercel",
        "canonical_slug": "vercel",
        "aliases": [],
        "editorial_kind": "platform",
        "topic_family": "frontend-platform",
        "implementation_languages": [],
        "ecosystems": ["edge", "web"],
        "description": "Application delivery platform tightly aligned with modern React and frontend workflows.",
    },
    {
        "canonical_name": "PostgreSQL",
        "canonical_slug": "postgresql",
        "aliases": ["postgres", "pg"],
        "editorial_kind": "platform",
        "topic_family": "data",
        "implementation_languages": ["c"],
        "ecosystems": ["database"],
        "description": "Relational data platform with strong extension ecosystem and multi-workload relevance.",
    },
    {
        "canonical_name": "Azure",
        "canonical_slug": "azure",
        "aliases": ["microsoft azure"],
        "editorial_kind": "platform",
        "topic_family": "cloud",
        "implementation_languages": [],
        "ecosystems": ["cloud"],
        "description": "Cloud platform with deep enterprise penetration and strong alignment with Microsoft-centric estates.",
    },
    {
        "canonical_name": "Google Cloud",
        "canonical_slug": "google-cloud",
        "aliases": ["gcp", "google cloud platform"],
        "editorial_kind": "platform",
        "topic_family": "cloud",
        "implementation_languages": [],
        "ecosystems": ["cloud"],
        "description": "Cloud platform often chosen for data, ML, and Kubernetes-heavy workloads.",
    },
    {
        "canonical_name": "Redis",
        "canonical_slug": "redis",
        "aliases": [],
        "editorial_kind": "platform",
        "topic_family": "data",
        "implementation_languages": ["c"],
        "ecosystems": ["database"],
        "description": "In-memory data platform widely used for caching, queues, and low-latency coordination patterns.",
    },
    {
        "canonical_name": "Snowflake",
        "canonical_slug": "snowflake",
        "aliases": [],
        "editorial_kind": "platform",
        "topic_family": "data-platform",
        "implementation_languages": [],
        "ecosystems": ["cloud", "data"],
        "description": "Cloud data platform with strong adoption for analytics, warehousing, and governed data sharing.",
    },
    {
        "canonical_name": "MongoDB",
        "canonical_slug": "mongodb",
        "aliases": ["mongo", "mongo db"],
        "editorial_kind": "platform",
        "topic_family": "data",
        "implementation_languages": ["c++"],
        "ecosystems": ["database"],
        "description": "Document database platform with broad developer adoption for flexible application data models.",
    },
    {
        "canonical_name": "Databricks",
        "canonical_slug": "databricks",
        "aliases": [],
        "editorial_kind": "platform",
        "topic_family": "data-platform",
        "implementation_languages": [],
        "ecosystems": ["cloud", "data"],
        "description": "Lakehouse platform with strong traction in data engineering, analytics, and applied AI workflows.",
    },
    {
        "canonical_name": "Apache Kafka",
        "canonical_slug": "kafka",
        "aliases": ["apache kafka", "kafka"],
        "editorial_kind": "platform",
        "topic_family": "streaming",
        "implementation_languages": ["java"],
        "ecosystems": ["cloud", "streaming"],
        "description": "Streaming backbone platform frequently used for event pipelines, integration, and real-time data movement.",
    },
    {
        "canonical_name": "Supabase",
        "canonical_slug": "supabase",
        "aliases": [],
        "editorial_kind": "platform",
        "topic_family": "developer-platform",
        "implementation_languages": [],
        "ecosystems": ["database", "web"],
        "description": "Developer platform centered on hosted Postgres and fast-moving backend capabilities for product teams.",
    },
    {
        "canonical_name": "Netlify",
        "canonical_slug": "netlify",
        "aliases": [],
        "editorial_kind": "platform",
        "topic_family": "frontend-platform",
        "implementation_languages": [],
        "ecosystems": ["edge", "web"],
        "description": "Frontend delivery platform still relevant for JAMstack-style workflows and fast web deployment loops.",
    },
    {
        "canonical_name": "OpenSearch",
        "canonical_slug": "opensearch",
        "aliases": ["elastic", "elasticsearch", "open search"],
        "editorial_kind": "platform",
        "topic_family": "search",
        "implementation_languages": ["java"],
        "ecosystems": ["data", "cloud"],
        "description": "Search and analytics platform commonly used for logging, observability, and application search use cases.",
    },
    {
        "canonical_name": "Neon",
        "canonical_slug": "neon",
        "aliases": [],
        "editorial_kind": "platform",
        "topic_family": "data-platform",
        "implementation_languages": [],
        "ecosystems": ["database", "cloud"],
        "description": "Serverless Postgres platform drawing attention for branchable database workflows and fast developer loops.",
    },
    {
        "canonical_name": "ClickHouse",
        "canonical_slug": "clickhouse",
        "aliases": [],
        "editorial_kind": "platform",
        "topic_family": "data-platform",
        "implementation_languages": ["c++"],
        "ecosystems": ["data", "cloud"],
        "description": "High-performance analytics platform increasingly used for product analytics, observability, and real-time reporting.",
    },
    {
        "canonical_name": "Platform Engineering",
        "canonical_slug": "platform-engineering",
        "aliases": ["internal developer platforms"],
        "editorial_kind": "technique",
        "topic_family": "operating-model",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Product-thinking approach to internal platforms and developer experience.",
    },
    {
        "canonical_name": "GitOps",
        "canonical_slug": "gitops",
        "aliases": [],
        "editorial_kind": "technique",
        "topic_family": "delivery",
        "implementation_languages": [],
        "ecosystems": ["cloud"],
        "description": "Declarative operations pattern driven by version-controlled desired state.",
    },
    {
        "canonical_name": "Retrieval-Augmented Generation",
        "canonical_slug": "rag",
        "aliases": ["retrieval augmented generation"],
        "editorial_kind": "technique",
        "topic_family": "ai",
        "implementation_languages": [],
        "ecosystems": ["ai"],
        "description": "Technique for grounding model outputs with retrievable context and data sources.",
    },
    {
        "canonical_name": "AI-Assisted Development",
        "canonical_slug": "ai-assisted-development",
        "aliases": ["ai coding", "copilot workflows"],
        "editorial_kind": "technique",
        "topic_family": "ai-devex",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Use of generative AI as a first-class collaborator in coding and review loops.",
    },
    {
        "canonical_name": "Contract Testing",
        "canonical_slug": "contract-testing",
        "aliases": [],
        "editorial_kind": "technique",
        "topic_family": "testing",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Verification pattern that stabilizes service boundaries without end-to-end overreach.",
    },
    {
        "canonical_name": "Observability",
        "canonical_slug": "observability",
        "aliases": [],
        "editorial_kind": "technique",
        "topic_family": "operations",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Operational practice focused on high-quality telemetry, debugging depth, and fast system understanding.",
    },
    {
        "canonical_name": "Feature Flags",
        "canonical_slug": "feature-flags",
        "aliases": ["feature flagging"],
        "editorial_kind": "technique",
        "topic_family": "delivery",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Release strategy that decouples deployment from exposure and supports safer progressive delivery.",
    },
    {
        "canonical_name": "Prompt Engineering",
        "canonical_slug": "prompt-engineering",
        "aliases": [],
        "editorial_kind": "technique",
        "topic_family": "ai",
        "implementation_languages": [],
        "ecosystems": ["ai"],
        "description": "Pattern of shaping instructions, context, and constraints to improve model behavior for real workflows.",
    },
    {
        "canonical_name": "Event-Driven Architecture",
        "canonical_slug": "event-driven-architecture",
        "aliases": ["eda"],
        "editorial_kind": "technique",
        "topic_family": "architecture",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Architectural style centered on asynchronous events, decoupled services, and reactive integration flows.",
    },
    {
        "canonical_name": "FinOps",
        "canonical_slug": "finops",
        "aliases": [],
        "editorial_kind": "technique",
        "topic_family": "operations",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Operational discipline for making cloud cost decisions visible, shared, and actionable across teams.",
    },
    {
        "canonical_name": "Shift-Left Testing",
        "canonical_slug": "shift-left-testing",
        "aliases": ["shift left testing"],
        "editorial_kind": "technique",
        "topic_family": "testing",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Practice of moving validation earlier into design and development feedback loops.",
    },
    {
        "canonical_name": "Zero Trust",
        "canonical_slug": "zero-trust",
        "aliases": ["zero trust"],
        "editorial_kind": "technique",
        "topic_family": "security",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Security model based on continuous verification rather than implicit trust from network location.",
    },
    {
        "canonical_name": "Model Context Protocol",
        "canonical_slug": "model-context-protocol",
        "aliases": ["mcp", "model context protocol"],
        "editorial_kind": "technique",
        "topic_family": "ai",
        "implementation_languages": [],
        "ecosystems": ["ai"],
        "description": "Emerging interoperability pattern for connecting models to tools, context sources, and external systems.",
    },
    {
        "canonical_name": "Agentic AI",
        "canonical_slug": "agentic-ai",
        "aliases": ["ai agents", "agentic systems"],
        "editorial_kind": "technique",
        "topic_family": "ai",
        "implementation_languages": [],
        "ecosystems": ["ai"],
        "description": "Pattern of orchestrating models with tools and multi-step control flow to complete bounded tasks.",
    },
    {
        "canonical_name": "Trunk-Based Development",
        "canonical_slug": "trunk-based-development",
        "aliases": ["trunk based development"],
        "editorial_kind": "technique",
        "topic_family": "delivery",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Delivery practice that favors short-lived branches and frequent integration to keep change flowing.",
    },
    {
        "canonical_name": "Data Contracts",
        "canonical_slug": "data-contracts",
        "aliases": ["data contracts"],
        "editorial_kind": "technique",
        "topic_family": "data",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Emerging practice for making data interfaces explicit, versioned, and operationally governable across teams.",
    },
    {
        "canonical_name": "Secure by Design",
        "canonical_slug": "secure-by-design",
        "aliases": ["secure by design"],
        "editorial_kind": "technique",
        "topic_family": "security",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Engineering approach that brings security decisions into architecture and implementation defaults from the start.",
    },
]


def get_seed_catalog() -> list[dict]:
    return deepcopy(SEED_ENTITIES)


def build_seed_lookup() -> dict[str, dict]:
    lookup: dict[str, dict] = {}
    for seed in SEED_ENTITIES:
        lookup[seed["canonical_slug"]] = seed
        lookup[seed["canonical_name"].strip().lower()] = seed
        for alias in seed.get("aliases", []):
            lookup[alias.strip().lower()] = seed
    return lookup
