from __future__ import annotations

from copy import deepcopy


SEED_ENTITIES: list[dict] = [
    {
        "canonical_name": "Python",
        "canonical_slug": "python",
        "aliases": ["py"],
        "editorial_kind": "language",
        "topic_family": "general-purpose",
        "implementation_languages": ["python"],
        "ecosystems": ["pypi"],
        "description": "General-purpose language with dominant reach across backend, data, and automation.",
    },
    {
        "canonical_name": "TypeScript",
        "canonical_slug": "typescript",
        "aliases": ["ts"],
        "editorial_kind": "language",
        "topic_family": "application",
        "implementation_languages": ["typescript", "javascript"],
        "ecosystems": ["npm"],
        "description": "Typed superset of JavaScript that anchors modern frontend and full-stack development.",
    },
    {
        "canonical_name": "Go",
        "canonical_slug": "go",
        "aliases": ["golang"],
        "editorial_kind": "language",
        "topic_family": "cloud",
        "implementation_languages": ["go"],
        "ecosystems": ["go"],
        "description": "Compiled language optimized for cloud services, infrastructure, and operational simplicity.",
    },
    {
        "canonical_name": "Rust",
        "canonical_slug": "rust",
        "aliases": ["rustlang"],
        "editorial_kind": "language",
        "topic_family": "systems",
        "implementation_languages": ["rust"],
        "ecosystems": ["cargo"],
        "description": "Memory-safe systems language increasingly used in infrastructure, tooling, and performance-sensitive services.",
    },
    {
        "canonical_name": "Java",
        "canonical_slug": "java",
        "aliases": [],
        "editorial_kind": "language",
        "topic_family": "enterprise",
        "implementation_languages": ["java"],
        "ecosystems": ["maven"],
        "description": "Enterprise runtime with broad platform support and sustained large-scale adoption.",
    },
    {
        "canonical_name": "React",
        "canonical_slug": "react",
        "aliases": ["reactjs"],
        "editorial_kind": "framework",
        "topic_family": "ui",
        "implementation_languages": ["javascript", "typescript"],
        "ecosystems": ["npm"],
        "description": "Component model that remains the default reference point for web UI engineering.",
    },
    {
        "canonical_name": "Next.js",
        "canonical_slug": "nextjs",
        "aliases": ["next.js", "next"],
        "editorial_kind": "framework",
        "topic_family": "web-platform",
        "implementation_languages": ["typescript", "javascript"],
        "ecosystems": ["npm"],
        "description": "Full-stack React framework with strong defaults for SSR, routing, and deployment integration.",
    },
    {
        "canonical_name": "FastAPI",
        "canonical_slug": "fastapi",
        "aliases": [],
        "editorial_kind": "framework",
        "topic_family": "api",
        "implementation_languages": ["python"],
        "ecosystems": ["pypi"],
        "description": "Python API framework favored for modern typed services and AI-adjacent backends.",
    },
    {
        "canonical_name": "Django",
        "canonical_slug": "django",
        "aliases": [],
        "editorial_kind": "framework",
        "topic_family": "web",
        "implementation_languages": ["python"],
        "ecosystems": ["pypi"],
        "description": "Mature batteries-included framework for web products and back-office systems.",
    },
    {
        "canonical_name": "Spring Boot",
        "canonical_slug": "spring-boot",
        "aliases": ["spring", "spring boot"],
        "editorial_kind": "framework",
        "topic_family": "enterprise",
        "implementation_languages": ["java", "kotlin"],
        "ecosystems": ["maven"],
        "description": "Default application framework for modern JVM services in large organizations.",
    },
    {
        "canonical_name": "Playwright",
        "canonical_slug": "playwright",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "testing",
        "implementation_languages": ["typescript", "python", "java", "c#"],
        "ecosystems": ["npm", "pypi", "maven", "nuget"],
        "description": "End-to-end testing tool with strong browser coverage and modern automation ergonomics.",
    },
    {
        "canonical_name": "Docker",
        "canonical_slug": "docker",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "containers",
        "implementation_languages": ["go"],
        "ecosystems": ["docker"],
        "description": "Container packaging toolchain that remains foundational to developer workflows.",
    },
    {
        "canonical_name": "Terraform",
        "canonical_slug": "terraform",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "infrastructure",
        "implementation_languages": ["go"],
        "ecosystems": ["terraform"],
        "description": "Infrastructure as code tool with broad enterprise footprint across cloud provisioning.",
    },
    {
        "canonical_name": "GitHub Actions",
        "canonical_slug": "github-actions",
        "aliases": ["github actions"],
        "editorial_kind": "tool",
        "topic_family": "delivery",
        "implementation_languages": ["yaml", "javascript"],
        "ecosystems": ["github"],
        "description": "Integrated CI/CD automation layer embedded in mainstream source control workflows.",
    },
    {
        "canonical_name": "Cursor",
        "canonical_slug": "cursor",
        "aliases": [],
        "editorial_kind": "tool",
        "topic_family": "ai-devex",
        "implementation_languages": ["typescript"],
        "ecosystems": ["desktop"],
        "description": "AI-assisted development environment shaping current developer workflow expectations.",
    },
    {
        "canonical_name": "AWS",
        "canonical_slug": "aws",
        "aliases": ["amazon web services"],
        "editorial_kind": "platform",
        "topic_family": "cloud",
        "implementation_languages": [],
        "ecosystems": ["cloud"],
        "description": "General-purpose cloud platform with the widest service surface and enterprise footprint.",
    },
    {
        "canonical_name": "Kubernetes",
        "canonical_slug": "kubernetes",
        "aliases": ["k8s"],
        "editorial_kind": "platform",
        "topic_family": "orchestration",
        "implementation_languages": ["go"],
        "ecosystems": ["cloud", "kubernetes"],
        "description": "Container orchestration platform that defines the control plane model for many teams.",
    },
    {
        "canonical_name": "Cloudflare",
        "canonical_slug": "cloudflare",
        "aliases": [],
        "editorial_kind": "platform",
        "topic_family": "edge",
        "implementation_languages": [],
        "ecosystems": ["edge"],
        "description": "Edge platform increasingly used for delivery, compute, and security consolidation.",
    },
    {
        "canonical_name": "Vercel",
        "canonical_slug": "vercel",
        "aliases": [],
        "editorial_kind": "platform",
        "topic_family": "frontend-platform",
        "implementation_languages": [],
        "ecosystems": ["edge", "web"],
        "description": "Application delivery platform tightly aligned with modern React and frontend workflows.",
    },
    {
        "canonical_name": "PostgreSQL",
        "canonical_slug": "postgresql",
        "aliases": ["postgres", "pg"],
        "editorial_kind": "platform",
        "topic_family": "data",
        "implementation_languages": ["c"],
        "ecosystems": ["database"],
        "description": "Relational data platform with strong extension ecosystem and multi-workload relevance.",
    },
    {
        "canonical_name": "Platform Engineering",
        "canonical_slug": "platform-engineering",
        "aliases": ["internal developer platforms"],
        "editorial_kind": "technique",
        "topic_family": "operating-model",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Product-thinking approach to internal platforms and developer experience.",
    },
    {
        "canonical_name": "GitOps",
        "canonical_slug": "gitops",
        "aliases": [],
        "editorial_kind": "technique",
        "topic_family": "delivery",
        "implementation_languages": [],
        "ecosystems": ["cloud"],
        "description": "Declarative operations pattern driven by version-controlled desired state.",
    },
    {
        "canonical_name": "Retrieval-Augmented Generation",
        "canonical_slug": "rag",
        "aliases": ["retrieval augmented generation"],
        "editorial_kind": "technique",
        "topic_family": "ai",
        "implementation_languages": [],
        "ecosystems": ["ai"],
        "description": "Technique for grounding model outputs with retrievable context and data sources.",
    },
    {
        "canonical_name": "AI-Assisted Development",
        "canonical_slug": "ai-assisted-development",
        "aliases": ["ai coding", "copilot workflows"],
        "editorial_kind": "technique",
        "topic_family": "ai-devex",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Use of generative AI as a first-class collaborator in coding and review loops.",
    },
    {
        "canonical_name": "Contract Testing",
        "canonical_slug": "contract-testing",
        "aliases": [],
        "editorial_kind": "technique",
        "topic_family": "testing",
        "implementation_languages": [],
        "ecosystems": ["org"],
        "description": "Verification pattern that stabilizes service boundaries without end-to-end overreach.",
    },
]


def get_seed_catalog() -> list[dict]:
    return deepcopy(SEED_ENTITIES)


def build_seed_lookup() -> dict[str, dict]:
    lookup: dict[str, dict] = {}
    for seed in SEED_ENTITIES:
        lookup[seed["canonical_slug"]] = seed
        lookup[seed["canonical_name"].strip().lower()] = seed
        for alias in seed.get("aliases", []):
            lookup[alias.strip().lower()] = seed
    return lookup

